### ISSUE TITLE
When I perform a breakpoint to continue training (resume) or model distillation to load an existing weight file, I find that torch.load() reads an error.

### ISSUE THREAD

**Issue by Williamwsk** [rasbt/cvpr2023#5]
The fabric parameters I use are as follows:
`fabric = L.Fabric(accelerator='cuda', precision='bf16-mixed', devices=torch.cuda.device_count(), strategy='FSDP')`
The model training and saving code is as follows:

```python
for epoch in range(start_epoch, opt.OPTIM.NUM_EPOCHS + 1):
        epoch_start_time = time.time()
        epoch_loss = 0
        train_id = 1
        model_restoration.train()
        for i, data in enumerate(tqdm(train_loader), 0):

            iter_loss = 0
            # zero_grad
            for param in model_restoration.parameters():
                param.grad = None

            if opt.TRAINING.DISTILL:
                if opt.TRAINING.ACCELERATE:
                    input_ = data[1]
                    target_ori = data[0]
                else:
                    input_ = data[1].cuda()
                    target_ori = data[0].cuda()
                with torch.no_grad():
                    target = teacher_model(input_)
            else:
                if opt.TRAINING.ACCELERATE:
                    input_ = data[1]
                    target = data[0]
                else:
                    input_ = data[1].cuda()
                    target = data[0].cuda()
            out = model_restoration(input_)
            loss_psnr = (1 + criterion_psnr(out, target) / 100)
            loss = loss_psnr
            if opt.TRAINING.ACCELERATE:
                fabric.backward(loss)
            else:
                loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
            iter_loss += loss_psnr.item()
            if i > 0 and i % print_freq == 0: print(f'\titer: {i}  loss: {epoch_loss:.4f}  iter_loss: {iter_loss:.4f}  iter_best psnr: 
               {iter_best_psnr:.4f}  loss_psnr:{loss_psnr:.4f}  learning rate:{scheduler.get_lr()[0]:.6f}')
            if i > 0 and i % step_iter == 0: scheduler.step()
            if iter_loss <= iter_best_psnr: # and -iter_loss < 100:
                iter_best_psnr = iter_loss
                torch.save({'epoch': epoch, 
                            'state_dict': model_restoration.state_dict(),
                            'optimizer' : optimizer.state_dict()
                            }, os.path.join(model_dir, "model_iter_best.pth"))

``` 
When I continued training (resume) from a breakpoint, I found that the weight of the model obtained by using lightning.Fabric training was 1/8 of the weight saved by pytorch training, and the weight saved by lightning.Fabric training could not be loaded.The error message is as follows:
```python
Traceback (most recent call last):
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/serialization.py", line 531, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/Code/Skin/train_distill_accelerate.py", line 351, in <module>
    main()
  File "/project/Code/Skin/train_distill_accelerate.py", line 212, in main
    utils.load_checkpoint_multigpu(model_restoration, path_chk_rest)
  File "/project/Code/Skin/utils/model_utils.py", line 38, in load_checkpoint_multigpu
    checkpoint = torch.load(weights)
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/serialization.py", line 440, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/serialization.py", line 425, in __init__
    _check_seekable(buffer)
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/serialization.py", line 534, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/serialization.py", line 527, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
``` 

And when I use the teacher model trained by lightning.Fabric to train the student model, the weights saved by lightning.Fabric are saved as follows when loading:
```python
Traceback (most recent call last):
  File "/project/Code/Skin/train_distill_accelerate.py", line 351, in <module>
    main()
  File "/project/Code/Skin/train_distill_accelerate.py", line 129, in main
    utils.load_checkpoint_multigpu(teacher_model, weights)
  File "/project/Code/Skin/utils/model_utils.py", line 45, in load_checkpoint_multigpu
    model.load_state_dict(new_state_dict)
  File "/root/anaconda3/envs/wsk-py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NAFNet:
	size mismatch for intro.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3]).
	size mismatch for intro.bias: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for ending.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([3, 32, 3, 3])......
``` 

The load_checkpoint_multigpu loading weight file function is as follows:
```python
def load_checkpoint_multigpu(model, weights):
    checkpoint = torch.load(weights)
    state_dict = checkpoint["state_dict"]
    new_state_dict = OrderedDict()
    for k, v in state_dict.items():
        name = k.replace('module.', '') if 'module' in k else k
        new_state_dict[name] = v
    model.load_state_dict(new_state_dict)
``` 

I would like to ask you how to save the model weights when using lightning.Fabric() to accelerate the model training code? How to load the model weights trained by lightning.Fabric() when resume or distillation? What is the difference between the weight file saved by lightning.Fabric() and the weight file saved by pytorch code? Why is the size of the former 1/8 of the latter? It seems that only the model structure is saved but not the training weight parameters of the model. Looking forward to your reply, best wishes!

**Comment by rasbt** [comment]
Good points. There are some saving and loading features that make saving and loading sharded models (via FSDP) easier. I will write up an answer for you in the next few days, but I want to check / implement this first with the code here to make sure it works before sharing.
